.codeclimate.yml

@codeclimate/review This PR updates engines in `.codeclimate.yml` config for this repo.

update .codeclimate.yml to use eslint

---

Dockerfile
package.json

/cc @codeclimate/review 
This fixes the recurring bugsnag as well as #10

Allow plugins to be loaded from /code/node_modules

---

circle.yml

@pbrisbin can you review this? I'll also need to know the values for the various environment variables (they are hidden in the CircleCI interface)

Add circle.yml file to build docker images on push

---

bin/eslint.js

Read config json from file

---

package.json

Upgrade ESLint to 24.1

---

bin/eslint.js
package.json

Exclude files before analysis begins

---

bin/eslint.js

Add remediation points

---

package.json

Diff of ESLint:
https://github.com/codeclimate/eslint/compare/b84e740...d8eb059
@codeclimate/review ping @brynary @noahd1

Allow React and Babel plugins.

---

bin/eslint.js

The spec requires this to be a hash with a "body" key

Fix content format

---

bin/eslint.js

_Follows #40 (accidentally closed due to empty branch push)_
Despite documentation from `node-glob` which states that symlinked
directories are not followed and crawled, that doesn't seem to be the
case, causing errors when listing files on CC or validating issues
emitted from ESLint regarding ignored files. This adds behavior to
manually prune any path within a symlink before analysis begins.

Prune files within symlinked paths

---

package.json

@codeclimate/review 
Diff: https://github.com/yannickcr/eslint-plugin-react/compare/v3.5.1...v3.6.3

Update react plugin

---

bin/eslint.js

Do the console redirect earlier

---

.codeclimate.yml

- Add duplication engine
- Rate checks file
@codeclimate/review @wfleming

Tweak Code Climate Config

---

Makefile

Add basic Makefile

---

package.json

Patches:
https://github.com/babel/babel-eslint/compare/v4.1.3...v4.1.8

Bump babel-eslint to 4.1.8

---

.codeclimate.yml

@codeclimate/review 
:lipstick:

Touch up .codelcimate.yml formatting

---

bin/eslint.js

We no longer provide these in any config visible to engines.

Remove `exclude_paths` support

---

bin/eslint.js
lib/compute_fingerprint.js
test/compute_fingerprint_test.js

This PR provides an fingerprint override for the complexity offenses incorporating the path, rule, and function name.

Add fingerprint override for complexity rule

---

Dockerfile
Makefile
circle.yml

Update CircleCI config to use patrick

---

Dockerfile
Makefile
circle.yml

Applying the same changes here as made in #97.

eslint-2: Update CircleCI config to use patrick 

---

package.json

Add eslint-config-google as available plugin

---

npm-shrinkwrap.json
package.json

Add support for using ESLint plugin to recognize [Flowtype](https://flowtype.org), [eslint-plugin-flowtype](https://github.com/gajus/eslint-plugin-flowtype).
Hope that the PR is fine, please let me know if there's some work left to do in order to include it.

Add support for ESLint plugin Flowtype

---

npm-shrinkwrap.json
package.json

Add `eslint-plugin-angular` to `eslint-2` channel.

eslint-2: Vendor eslint-plugin-angular package

---

README.md

Update badge url now that repo is open source on Code Climate.

Update cc badge reference

---

npm-shrinkwrap.json
package.json

Diff: https://github.com/yannickcr/eslint-plugin-react/compare/v5.1.1...v5.2.2

eslint-2: Bump eslint-plugin-react to v5.2.2

---

npm-shrinkwrap.json
package.json

Bump eslint to 3.6.1 & eslint-plugin-import to 1.16.0

---

README.md

As requested in #144. I also submitted a PR to the CodeClimate doc site.
/cc @dblandin

Add ignore_warnings to README

---

CONTRIBUTING.md

It come from the documentation : https://docs.codeclimate.com/docs/example-codeclimateyml

Fix .codeclimate.yml example in contributing

---

npm-shrinkwrap.json
package.json

- Upgrade eslint to 3.11.1
- Add eslint-config-simplifield

Add support for eslint-config-simplifield

---

package.json
yarn.lock

Close #155
Just ran: `bin/yarn add eslint-plugin-meteor`

Add eslint-plugin-meteor

---

package.json
yarn.lock

Add a few plugins

---

.eslintrc
bin/eslint.js
lib/config_upgrader.js
lib/eslint-patch.js
test/config_upgrater_test.js

Automatically upgrade pre-ESLint 3 config to ESLint 3-compatible format.
Upgrade instructions are directed to stderr.

Config upgrader

---

bin/eslint.js
lib/config_upgrader.js
lib/validate_config.js
test/config_upgrater_test.js

Reverting my change and using @pointlessone's instead

Gd config updater

---

lib/check_category_mapping.json
package.json
yarn.lock

Adds the [ESLint plugin for React Native](https://www.npmjs.com/package/eslint-plugin-react-native)

Add react-native plugin

---

Makefile
package.json

`make test NPM_TEST_TARGET=test.debug`

Easier debugging

---

package.json
yarn.lock

Adds support for the inferno eslint package - eslint-plugin-inferno.

Adds Support for `eslint-plugin-inferno`

---

package.json
yarn.lock

Update babel-eslint to 7.2.0

---

bin/eslint.js
integration/eslint_test.js
lib/eslint.js

@wfleming this seems to be a good alternative, testable and performant

Keep it testable with no performance penalty

---

package.json
yarn.lock

Update eslint-config-simplifield to the latest version 🚀

---

package.json
yarn.lock

Upgrade eslint-config-airbnb-base to v11.1.2

---

package.json
yarn.lock

https://github.com/eslint/eslint/compare/v3.18.0...v3.19.0

Bump eslint to v3.19.0

---

package.json
yarn.lock

Greenkeeper/eslint config standard 10.0.0

---

lib/check_category_mapping.json
package.json
yarn.lock

See: https://github.com/facebook/jest/tree/master/packages/eslint-plugin-jest

Add support for eslint-plugin-jest

---

package.json
yarn.lock

We fully replaced this with a custom implementation in:
https://github.com/codeclimate/codeclimate-eslint/pull/226

Remove circleci-update-yarn-lock

---

package.json
yarn.lock

Add support for laws of the game plugin

---

package.json
yarn.lock

Greenkeeper/eslint plugin html 2.0.3

---

package.json
yarn.lock

Opened via https://github.com/codeclimate/codeclimate-eslint/pull/268#issuecomment-302064568

Greenkeeper/eslint plugin jest 20.0.3

---

package.json
yarn.lock

https://github.com/gajus/eslint-plugin-flowtype/compare/v2.30.3...v2.34.0
* Add no-types-missing-file-annotation rule
* Fix no-dupe-keys rule
Addresses https://github.com/codeclimate/codeclimate-eslint/issues/285

Update eslint-plugin-flowtype to v2.34.0

---

README.md
integration/eslint_test.js
lib/engine_config.js
lib/eslint.js
test/engine_config_test.js

Add option to disable file sanitization

---

package.json
yarn.lock

https://github.com/Rantanen/eslint-plugin-xss

Add XSS plugin

---

package.json
yarn.lock

[eslint-plugin-unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn) add various rules to ESLint

Add support for eslint-plugin-unicorn

---

package.json
yarn.lock

[eslint-plugin-eslint-comments](https://github.com/mysticatea/eslint-plugin-eslint-comments) add rules for directive comments of ESLint.

Add support for eslint-plugin-eslint-comments

---

package.json
yarn.lock

Let's try this again : ) 
Upgrade `eslint-plugin-ember` to 4.5.0.

Retry: upgrade eslint-plugin-ember to version 4.5.0

---

package.json
yarn.lock

Fixes https://github.com/codeclimate/codeclimate-eslint/issues/367

Bumps babel-eslint to 8.2.1 on channel/eslint-4

---

package.json
yarn.lock

Support for eslint-ramda-plugin (#369)
This has not yet been tested locally. Will update PR with status.

Adding support for eslint-plugin-ramda

---

package.json
yarn.lock

Bump eslint-plugin-vue to 4.2.2.

Bump eslint-plugin-vue

---

package.json
yarn.lock

Close #351 (this replaces that one)

[eslint-4] update prettier

---

package.json
yarn.lock

https://github.com/bleacherreport/eslint-plugin-laws-of-the-game
cc Dave H

use v1.3.0 of @br/eslint-plugin-laws-of-the-game

---

package.json
yarn.lock

Re: https://github.com/codeclimate/codeclimate-eslint/issues/390

Add eslint-plugin-coffeescript

---

package.json
yarn.lock

Add `eslint-plugin-cypress` to resolve issue https://github.com/codeclimate/codeclimate-eslint/issues/366

add eslint-plugin-cypress

---

package.json
yarn.lock

- Adds eslint-plugin-chai-friendly (requested here: https://github.com/codeclimate/codeclimate-eslint/issues/406)

Add eslint-plugin-chai-friendly

---

package.json
yarn.lock

update eslint-plugin-prettier on master

---

package.json
yarn.lock

update **eslint-config-prettier** on master to solve https://github.com/codeclimate/codeclimate-eslint/issues/383#issuecomment-382232888

update eslint-config-prettier on master

---

package.json
yarn.lock

Update **eslint-config-prettier** to solve https://github.com/codeclimate/codeclimate-eslint/issues/383#issuecomment-382232888

update eslint-config prettier ch4

---

package.json
yarn.lock

1. Revert airbnb and airbnb-base upgrades. 
2. Add chai friendly to ch4.

add chai friendly ch4

---

package.json
yarn.lock

[Channel-5] Add webpack (4.25.1)

---

package.json
yarn.lock

Fixes #442 
https://eslint.org/blog/2019/01/future-typescript-eslint

Add typescript-eslint parser and plugin

---

package.json
yarn.lock

* adds `"eslint-plugin-react-hooks"` to `package.json`
* adds `"eslint-plugin-react-hooks"` to `yarn.lock`

Add eslint-plugin-react-hooks to channel/eslint-4

---

package.json
yarn.lock

Fix https://github.com/codeclimate/codeclimate-eslint/issues/457

Upgrade typescript related libs to get better integration with Prettier

---

.codeclimate.yml
package.json
yarn.lock

I tested this on real-world repos.

Add ESLint-7 support

---

package.json
yarn.lock

Related to https://github.com/codeclimate/codeclimate-eslint/pull/493

QUAPL-45: update typescript

---

package.json
yarn.lock

Upgrading eslint-plugin-jsdoc in channel/eslint-5 to hopefully resolve the issues in #501

upgrade eslint-plugin-jsdoc to 30.7.3 (ESLint 5)

---

package.json
yarn.lock

Hey,
I updated @typescript-eslint to the newest version. Will appreciate if you can merge it!

Update @typescript-eslint to the latest version

---

package.json
yarn.lock

https://codeclimate.atlassian.net/browse/QUA-143

QUA-143: Update eslint-plugin-react

---

integration/eslint_test.js
lib/eslint6-patch.js
test/eslint6-patch_test.js

Same as https://github.com/codeclimate/codeclimate-eslint/pull/509

QUA-146: Fix no rules configured warning 

---

Dockerfile
package.json
yarn.lock

https://codeclimate.atlassian.net/browse/QUA-167

Support @babel/eslint-parser

---

package.json
yarn.lock

Add react-perf plugin support

---

package.json
yarn.lock

This is something heavily relied upon by us at https://github.com/PicoNetworks
Please let us know if there's any issues getting this merged in as soon as you can. :pray:

Add @babel/plugin-transform-runtime support

---

package.json
yarn.lock

Hello! Still seeing some errors for this other plugin not currently supported. I appreciate the help getting this merged in. :raised_hands:

add @babel/plugin-proposal-class-properties support

---

package.json
yarn.lock

Sorry, I think this is our last one. :grimacing: :pray: 
Thank you so much!

fix: add support for babel-plugin-react-generate-property

---

package.json
yarn.lock

Addresses https://github.com/codeclimate/codeclimate-eslint/issues/517

Eslint vue 7x upgrade

---

package.json

Upgrade eslint channel 7 to version 7.8.1
https://codeclimate.atlassian.net/jira/software/projects/QUA/boards/44?selectedIssue=QUA-184

Upgrade: eslint to version 7.8.1

---

README.md
package.json
yarn.lock

Add [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter/) to eslint-7 channel
[Source files here](https://github.com/formatjs/formatjs/tree/main/packages/eslint-plugin-formatjs)

Add eslint-plugin-formatjs plugin

---

bin/docs
package.json
yarn.lock

Jira Ticket: https://codeclimate.atlassian.net/browse/QUA-1077

Eslint 8.36.0
