codeclimate/codeclimate-eslint

bin/eslint

@codeclimate/review This PR adds the ability for users to add extensions under an `extensions` key in their eslint engine in .codeclimate.yml file. It keeps `.js` as a default extension if none is provided.

update engine config to allow users to add elements to under key extensions

---

bin/eslint

/cc @codeclimate/review 
In the case of a fatal error, the ruleId is not set: http://eslint.org/docs/developer-guide/nodejs-api.html#linter
> ruleId - the ID of the rule that triggered the messages (or null if fatal is true).
This sets it so that the engine matches the spec

Set the check name when there is a fatal error

---

Dockerfile
package.json

/cc @codeclimate/review 
[These ESLint commits](https://github.com/codeclimate/eslint/compare/v0.24.1...c5457c8?diff=unified&name=c5457c8) disable requiring of plugins and shared configs, until we can support them in the future.

Update eslint to our fork

---

bin/eslint.js

This is part of https://trello.com/c/93amREzt/751-eslint-performance-issue-discrepency-between-local-and-bbg
@GordonDiggs does this kind of look like what you were thinking?
Output looks like:
```
eslint.timing.engineConfig: 0s
eslint.timing.fileWalk: 0.003s
eslint.timing.cliInit: 0s
eslint.timing.cliRun: 0.001s
eslint.timing.resultsOutput: 0s
```

output some perf timing to stderr

---

bin/eslint.js

For the time being, engines need to support both the old `include_paths` and the new `exclude_paths` keys in `config.json`. This PR represents that requirement.

Update to handle config.include_paths or config.exclude_paths.

---

package.json

This PR points the eslint dependency to an updated fork, which now includes upstream changes (including new configuration options) added up to the [v1.5.1](https://github.com/eslint/eslint/releases/tag/v1.5.1) release.
Closes #23

Use updated ESLint fork with support for new configuration options

---

.codeclimate.yml
bin/eslint.js

ESLint emits a warning when a path, ignored with `.eslintignore`, is passed explicitly for analysis. The issue formatted by this engine doesn't pass validation and causes the engine to error out. This PR delegates to the CLIEngine's `#isPathIgnored` function to determine whether a file path is ignored by `.eslintignore`. If so, we'll write a warning out to STDERR instead of formatting an issue.

Warn via STDERR when ESLint is ignoring a path included by `.codeclimate.yml`

---

.dockerignore
.gitignore
bin/eslint.js
bin/node_gc

This may help with our memory consumption issues with the eslint engine in production. I'm forcing GC at intervals.
I ran this locally against the [meteor/meteor](https://github.com/meteor/meteor) repository locally to test. I verified that analysis results were identical with & without batching. I got a rough sense of memory consumption by watching `top` in my docker VM while analysis ran, and the batching seemed to bring down peak memory usage by ~500mb, which is nothing to sneeze at.
Worth mentioning I did try this *without* GC-forcing first, and memory usage was basically unchanged from `master`. I'm not sure whether blame for this lies with node itself or something eslint does internally, but something is a bit strange with the default GC behavior, I think.
cc @codeclimate/review @jp …

Process files in batches, force garbage collection

---

bin/eslint.js

As of 0.8.1, the CLI supports this format:
https://github.com/codeclimate/codeclimate/releases/tag/v0.8.1
This fixes specifying extensions to be analyzed by ESLint

Update location of configuration to match codeclimate.

---

bin/eslint.js

Hi there - I ran into this error:
```
error: (CC::Analyzer::Engine::EngineFailure) engine eslint failed with status 1 and stderr
eslint.timing.engineConfig: 0s
/usr/src/app/bin/eslint.js:56
&& extensions.indexOf(extension) >= 0
^
TypeError: Cannot read property 'indexOf' of undefined
at isFileWithMatchingExtension (/usr/src/app/bin/eslint.js:56:18)
at /usr/src/app/bin/eslint.js:83:48
at Array.forEach (native)
at /usr/src/app/bin/eslint.js:80:14
at /usr/src/app/bin/eslint.js:153:10
at runWithTiming (/usr/src/app/bin/eslint.js:12:12)
at Object.<anonymous> (/usr/src/app/bin/eslint.js:152:21)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
```
Presumably exclusionBasedFileListBuilder should be passing `extensions` to …

Fix “Cannot read property 'indexOf' of undefined” in exclusionBasedFileListBuilder

---

bin/eslint.js

Some ESLint functions (namely cli.isPathIgnored) depend on relative
paths, so if we aren't cd'd into /code, it can't find the .eslintignore
file correctly.
@codeclimate/review @mrb

Change directory to /code before running analysis.

---

bin/eslint.js
package.json

Once ESLint is updated to return a `docs` object containing rule
name and doc content:
(PR: https://github.com/codeclimate/eslint/commit/52701b16a36924df16705266992ef4585a36ea25)
we can easily access that data for issue content.
ESLint rule markdown docs here:
https://github.com/eslint/eslint/tree/master/docs/rules
If no doc is found, the content defaults to a suggestion to
read more at Source: http://eslint.org/docs/rules/
cc @codeclimate/review @mrb @jpignata

Add content for issues

---

package.json

The previous one lost the prefix whitelist
Diff:
https://github.com/eslint/eslint/compare/2bbebe6...65c744a54073e72fa1f10d2b43fa171aadea59d6

Update ESLint commit

---

bin/eslint.js
lib/checks.js

@codeclimate/review 
Each commit is reviewable separately.

Categories / Remediation points

---

bin/eslint.js

If a user sets `debug: true` in `.codeclimate.yml`, print each file to stderr before analyzing it.

Debug mode

---

package.json

This bumps the version of `codeclimate/eslint` which now whitelists
Airbnb. This also adds `eslint-config-airbnb` to `package.json` so
projects that extend the airbnb config will work.

Add support for Airbnb config

---

package.json

Comparison:
https://github.com/codeclimate/eslint/compare/650b41876e2d0b582f65b9056952c728097c58f6...9dba1feb51493d406a55f8bad6ca0d0713c71d7e
/c @codeclimate/review

Track version 1.9.0 of eslint

---

package.json

Full changes here:
https://github.com/codeclimate/eslint/commit/d24d0b451b75cfad304faeb394371096f2c90777
Original impetus was an error caused by eslint out of date on a snapshot.
Note that in addition to regular updates, this change to our eslint fork required
rewriting the line that permits airbnb packages but no others.
cc @codeclimate/review 
same as https://github.com/codeclimate/codeclimate-eslint/pull/50
Wanted to practice cross-repo pulls

update eslint fork to release 1.10.3 of eslint

---

bin/eslint.js

This ensures that we are the only ones writing to STDOUT during the run
of the container, and 3rd party `console.log` statements will be
redirected to STDERR.
Proof that it ends up in STDERR:
```
~/cc/codeclimate-eslint (master) 🐖  docker logs 9babbd74e0dd > /dev/null
eslint.timing.engineConfig: 0s
eslint.timing.buildFileList: 1.376s
The react/jsx-quotes rule is deprecated. Please use the jsx-quotes rule instead.
eslint.timing.analyze-batch-0: 0.781s
eslint.timing.report-batch0: 0s
```

Redirect console.log to console.error

---

.eslintrc
bin/eslint.js
lib/checks.js

The current eslintc is useless.
cc @gordondiggs @codeclimate/review

Add app's eslintrc

---

bin/eslint.js

`console.log` does some extra work to construct the output, and because
it's already a string, we can save some memory by using
`process.stdout.write`. See this issue for more information:
https://github.com/nodejs/node/issues/1741#issuecomment-103827443
This is an attempt to remedy the OOM issues when rendering all the
issues. Increasing the batch size will also help by reducing the number
of GCs.

Use process.stdout.write instead of console.log and increase batch size

---

Dockerfile
Makefile

Both of these are small best practice things.
1. Use a tag on our base image to reduce chance of random breakage
2. Add maintainer info
:eyes: @codeclimate/review

Dockerfile: use tag for base image, add maintainer

---

bin/eslint.js

"fatal" issues that eslint reports might not have column/linenumbers.
This is invalid by the engine spec, so we should avoid it.

Default line/column when null

---

bin/eslint.js

Similar to the approach we took for Radon, this is helpful output to
guide users who might need babel toward the info they would need.
cc @codeclimate/review

Log the parser we're using at run time

---

bin/eslint.js

Only output timing information if debug is set to true.

---

bin/eslint.js
lib/validate_config.js
package.json
test/fixtures/config/.eslintrc.js
test/validate_config_test.js

If there is no eslintrc.* file, ESLint's behavior is to do nothing (and
therefore emit no issues). Because this can be confusing, we should fail
hard and show helpful information.

Error if there is not a valid configuration file

---

bin/eslint.js

We saw a bug with `.eslintignore`: when we tested whether a file was
being ignored, we passed the relative directory (which is correct, and
produces expected behavior), but when we actually passed the file for
analyiss, we were passing the absolute path. Thus, a file that actually
should not have been ignored was detected as ignored by eslint when
asked to analyze it.
The changes here keep file paths relative for the most part: we chdir to
/code before we do just about anything else, so this works well. I also
extracted all the remaining usage of "/code" to a global var just for
organizational purposes.

Keep paths relative to /code

---

bin/eslint.js

Where it was currently instantiated was before the options have been fully
inflated from a possible engine config. This meant that any configured
configFile or extensions would be ignored.
/cc @codeclimate/review

Delay instantiation of cli variable

---

bin/eslint.js

The default behavior of eslint --config is to use that config _in addition to_
any default config (e.g. .eslintrc), not _instead of_. To prevent this, you
have to additionally pass --no-eslintrc.
We find this behavior surprising and prefer setting a custom config to also
imply --no-eslintrc, despite being a behavior difference between the engine and
the underlying tool.
/cc @codeclimate/review
This came out of a CX report. I'm open to opinions if departing from the
default behavior of eslint is actually worthwhile. Another option is to somehow
influence --no-eslintrc via codeclimate.yml.

Behave like --no-eslintrc if custom config is present

---

Dockerfile
npm-shrinkwrap.json
package.json

[Standard Style][] is a commonly adopted style for writing JavaScript. We hope
to support other [third-party plugins][] and [shared configurations][] in the
future without needing to vendor them in but this update removes a blocker for
a bunch of users and I think it's popular enough to warrant pulling into the
engine.
[Standard Style]: http://standardjs.com/
[third-party plugins]: https://github.com/codeclimate/codeclimate-eslint/issues/86
[shared configurations]: https://github.com/codeclimate/codeclimate-eslint/issues/4

Support standard style ESLint shared config and plugin

---

Dockerfile
npm-shrinkwrap.json
package.json

_This applies a similar update (with different version numbers) from #95 to the `eslint-2` channel._
Standard Style is a commonly adopted style for writing JavaScript. We hope
to support other third-party plugins and shared configurations in the
future without needing to vendor them in but this update removes a blocker for
a bunch of users and I think it's popular enough to warrant pulling into the
engine.
@codeclimate/review 🔎

eslint-2: Support standard style ESLint shared config and plugin

---

Dockerfile

Related to #111, a Segfault occurs when we hammer STDOUT with issues.
Switching from alpine to a debian-based image seems to behave better in
this scenario.

Switch base image to avoid Segfault

---

npm-shrinkwrap.json
package.json

We're a bit behind on these. Flowtype in particular has new rules we
weren't supporting.
Looks like we hadn't actually filled in the shrinkwrap file before now,
either, so that's done.
cc @codeclimate/review

Update babel-eslint & eslint-flowtype

---

.eslintrc
bin/eslint.js
test/checks_test.js
test/validate_config_test.js

- Update eslint configuration
- Reduce complexity via temporary variable
- Consistent brace style
Extracted from #109. Will cherry-pick into eslint-2 after merging.

Code cleanup

---

bin/eslint.js

Makes it possible to use ignorePath from the CLIEngine. Useful when you
are already ignoring the files you don't want to lint in different file
(.e.g .gitignore).
/cc @codeclimate/review
Extracted from #109.

Support for ignore_path in engine config

---

package.json

eslint-config-airbnb-base is a transitive dependency of eslint-config-airbnb, but it is useful in its own right and should be included at the top level such that it has proper support in the eslint engine.
As-is, I can use eslint-config-airbnb-base as an eslint plugin in my project and it works, but this is more than likely due to npm 3's new behavior of installing modules flat instead of nested.
This did not require a change to the npm-shrinkwrap.json. I ran `npm shrinkwrap` after installing this package and it didn't change the shrinkwrap at all.

Add eslint-config-airbnb-base as a top-level dep

---

npm-shrinkwrap.json
package.json

The [original](https://github.com/dockyard/ember-suave) jscs flavor of ember-suave is the [27th most used addon](https://emberobserver.com/addons/ember-suave) in the EmberJS ecosystem. As of a few weeks ago, this configuration has migrated to an eslint-plugin ([eslint-plugin-ember-suave](https://github.com/DockYard/eslint-plugin-ember-suave)) and they plan to make this [the default for the ember suave plugin](https://github.com/DockYard/ember-suave/issues/113).
For the ember community, this is an excellent addition and, for my team, it's required to use codeclimate on our projects.
Merging this PR would resolve #139

Add ember-suave plugin

---

npm-shrinkwrap.json
package.json

This commit adds two npm packages that support [eslint-plugin-import][].
[eslint-plugin-import]: https://github.com/benmosher/eslint-plugin-import
- [eslint-import-resolver-webpack][]
- [eslint-import-resolver-node][]
[eslint-import-resolver-webpack]: https://www.npmjs.com/package/eslint-import-resolver-webpack
[eslint-import-resolver-node]: https://www.npmjs.com/package/eslint-import-resolver-node
More details on how [eslint-plugin-import][] implements resolvers can be
found [in its README][resolvers].
[resolvers]: https://github.com/benmosher/eslint-plugin-import#resolvers
Addresses https://github.com/codeclimate/codeclimate-eslint/issues/143

Add eslint-plugin-import resolvers for node and webpack

---

CONTRIBUTING.md
bin/eslint.js

Since `--quiet` is [not a supported configuration](https://github.com/eslint/eslint/issues/1768) for the CLIEngine, I think this is how we'll have to address #142 .
Outstanding Questions:
~~* [ ] automated testing - is there any that can be added for this?~~
Integration testing seems out of scope for this change
~~* [ ] docs - where should this config option be documented?~~
docs website needs to be updated

Allow ignoring warnings from configuration.

---

npm-shrinkwrap.json
package.json

This reverts commit ac35f7ea4984c3124ad8451d952cb3c41a75c171.
Unfortunately, this behavior doesn't seem to work when modules are
imported in source code but not installed via npm, as is the case when
running static analysis builds on codeclimate.com.

Revert "Add eslint-plugin-import resolvers for node and webpack"

---

package.json
yarn.lock

This replaces https://github.com/codeclimate/codeclimate-eslint/pull/158 -- I borrowed @mike-schultz's commit and ran the `yarn` command to update the `yarn.lock` as well.

Upgrade eslint-config-google to 0.7.1

---

package.json
yarn.lock

`bin/yarn add eslint-config-semistandard`
adds [semistandard](https://github.com/Flet/eslint-config-semistandard) which is the semicolon-appreciating variant of [standard](https://github.com/feross/eslint-config-standard).

Add eslint-config-semistandard

---

lib/config_upgrader.js
test/config_upgrater_test.js

When upgrader encountered a project that had no `.eslintrc*` but had an unrelated `package.json` that had no ESLint-related options in it an exception was thrown.

Fix null-config issue with upgrader

---

bin/eslint.js
lib/config_upgrader.js
lib/validate_config.js
test/config_upgrater_test.js

Upgrader improperly kept detecting ESLint config file when engine had a specific config file specified.
This behaviour resulted in providing upgrade instructions for the wrong config file or in worse case trowing an exception of missing config file.

Fix upgrader with specified ESLint config

---

lib/config_upgrader.js
test/config_upgrater_test.js

Fixes the following error:
TypeError: Reduce of empty array with no initial value
at Array.reduce (native)
at Function.upgradeInstructions (/usr/src/app/lib/config_upgrader.js:272:20)
at Object.<anonymous> (/usr/src/app/bin/eslint.js:239:37)
at Module._compile (module.js:556:32)
at Object.Module._extensions..js (module.js:565:10)
at Module.load (module.js:473:32)
at tryModuleLoad (module.js:432:12)
at Function.Module._load (module.js:424:3)
at Module.runMain (module.js:590:10)
at run (bootstrap_node.js:394:7)
I couldn't find a good initial value to give to `reduce` to obtain the
correct functionality. There's no reason to reduce anyway if there are
no reports.

Fix error when there are no config files

---

Dockerfile

Locally while working with Abby to add a plugin, we noticed some
permissions errors in yarn. Downgrading to the stable release resolves
those errors for me.
We were using the nightly release for a bug fix that has since been
released on stable:
https://github.com/codeclimate/codeclimate-eslint/pull/159#issuecomment-266857865

Use stable yarn release

---

package.json

Hey,
I tried to build my repository on codeclimate and it seems like that `eslint-plugin-vue` and `eslint-plugin-html` is missing.
I hope this PR will fix the issue.

Add eslint-plugin-vue and eslint-plugin-html

---

package.json
yarn.lock

The eslint plugin for filenames allows you to verify that users are following a naming convention. For example, npm modules generally follow the kebab-case convention.
At my company, we specifically enforce this in part because there are differences in case-sensitivity across operating systems. Whereas on OSX, filenames are not case-sensitive, they **ARE** on Linux.
This is a plugin with significant backing (for example, [Walmart](https://github.com/walmartlabs/eslint-config-defaults/blob/master/package.json#L22))

Add support for eslint-plugin-filenames

---

package.json
yarn.lock

7.0.0 uses a configuration that isn't compatible with our version of
eslint (3.14.1) and results in schema errors.
We can upgrade to a newer eslint-config-standard when we upgrade to a
newer eslint.

Downgrade eslint-config-standard

---

bin/eslint.js
lib/docs.js
lib/empty-plugin.js
lib/eslint-patch.js
package.json
test/eslint-patch_test.js
yarn.lock

Fix #192 
Instead of erroring and aborting the execution,
the engine now prints a warning and skip the plugin
Given an .eslintrc.yml:
```yaml
env:
es6: true
node: true
parserOptions:
sourceType: module
plugins:
- node
- not_supported
extends:
- not_valid
- 'plugin:invalidplugin/recommended'
- 'eslint:recommended'
- 'plugin:node/recommended'
rules:
invalidplugin/rule: 1
node/exports-style: [error, module.exports]
indent: [error, 4]
linebreak-style: [error, unix]
quotes: [error, double]
semi: [error, always]
no-console: off
```
When `CODECLIMATE_DEBUG=true codeclimate analyze` runs
Then the output is like:
```
...
Module not supported: eslint-plugin-not_supported
Module not supported: eslint-plugin-invalidplugin
Module not supported: eslint-config-not_valid
...
Analyzing: app1.js
...
== …
```

Do not raise error on unsupported plugins

---

package.json
yarn.lock

Updating our `eslint-plugin-xogroup` to version `1.2.0`.  The method for updating this was done through `bin/yarn upgrade`. 
* `package.json`
* `yarn.lock`

updated eslint-plugin-xogroup to 1.2.0

---

bin/eslint.js

These warnings generate a lot of noise and obfuscate useful error
messages in errored build output.
We can let ESLint handle ignored file behavior instead of pruning the
paths up front ourselves.

Remove file is ignored by `.eslintignore` warnings

---

.codeclimate.yml
bin/yarn

- Update bin/yarn executable
- Specify current user id/group within container to fix write permission errors
- Simplify docker run invocation
- Add shellcheck engine to codeclimate analysis
Addresses https://github.com/codeclimate/codeclimate-eslint/issues/173#issuecomment-286965537
```
$ bin/yarn add eslint-plugin-html
yarn add v0.21.3
[1/4] Resolving packages...
[2/4] Fetching packages...
error Could not write file "/usr/src/app/yarn-error.log": "EACCES: permission denied, open '/usr/src/app/yarn-error.log'"
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
error An unexpected error occurred: "EACCES: permission denied, unlink '/usr/src/app/node_modules/.yarn-integrity'".
```

Update yarn executable

---

Dockerfile
bin/docs
engine.json

Currently, the apt-get package install layer is invalidated anytime we
update npm dependencies. This commit splits package installation and npm
dependency installation into separate steps, which should improve docker
layer caching and speed up build times.
This commit also extracts the inline docs installation into a separate
bin script.

Improve docker layer caching and build times

---

circle.yml
package.json
yarn.lock

Uses a `greenkeeper-*` branch deployment step and the [circleci-update-yarn-lock][] package to update the `yarn.lock` file and push an update to the branch.
Planning on bumping the [two](https://github.com/codeclimate/codeclimate-eslint/pull/219) [open](https://github.com/codeclimate/codeclimate-eslint/pull/220) greenkeeper PRs to test this after merging.
Note: Requires the addition of a deploy key with write access: https://circleci.com/docs/1.0/adding-read-write-deployment-key/
[circleci-update-yarn-lock]: https://github.com/clarkbw/circleci-update-yarn-lock

Update yarn.lock file automatically for greenkeeper PRs

---

bin/docs

This commit simplifies the bin/docs script clone step by using --branch
to reset to the specified version.

Clone eslint and checkout to version in one step

---

bin/circleci-update-yarn-lock
circle.yml
package.json

This commit updates our CI setup to use local bin script instead of the
[npm module I found][module] to update the yarn.lock file on greenkeeper
package update PRs.
- While cross-origin PRs don't have access to project secrets,
installing and executing an external module in a step that has push
access to the repo on GitHub seemed risky
- yarn generate-lock-file does not fully resolve the modules and
confusingly generates a differently formatted yarn.lock file
[yarnpkg/yarn#2340][issue]
- Run a full yarn install so that a expected yarn.lock is
generated/updated
[issue]: https://github.com/yarnpkg/yarn/issues/2340
[module]:https://github.com/clarkbw/circleci-update-yarn-lock

Use bin script to update yarn.lock via CircleCI

---

integration/ignore_warnings/eslintrc.js
integration/ignore_warnings/index.js
integration/ignore_warnings_test.js
lib/engine_config.js
lib/eslint.js
test/engine_config_test.js

Due to some oddness with our `cc-yaml` parser right now, all keys under `config` for an engine are parsed as strings. The engine did not take this into account when inspecting boolean config options `debug` and `ignore_warnings`, which basically meant explicitly specifying *any* value for these flags was always interpreted as `true`, and the only way to get `false` was to not specify the flag at all (since both values default to `false`). (Or you could specify the value as `""` in YAML, since `!!""` is `false` in JS, but that's a dumb hack.)
I started here by writing some red tests & extracting the config behavior out of `lib/eslint.js`, then fixing the bug there to see tests change.
I'll squash up commits before merging.

Fix boolean config flags behavior

---

Dockerfile

This commit updates the final location of the engine specification file
`engine.json` to `/` instead of the engine source code directory
`/usr/src/app`, as required by the Code Climate spec:
https://github.com/codeclimate/spec/blob/master/SPEC.md#engine-specification-file

Save engine.json specification file to /, not /usr/src/app

---

lib/config_finder.js
lib/config_upgrader.js
lib/eslint-patch.js
lib/eslint.js
lib/rule_blocklist.js
test/config_finder_test.js
test/config_upgrater_test.js
test/rule_blocklist_test.js

Add a way to disable rules.
One particular case is #222.

Rule Blocklist

---

lib/rule_blocklist.js
test/rule_blocklist_test.js

As per [comment](https://github.com/codeclimate/codeclimate-eslint/pull/231#issuecomment-291585702) in #231, here's update to rule blocklist.
Remove:
* `import/extensions` — it does not fail when can not resolve module, uses  literal value instead
* `import/no-absolute-path` — does not use module resolution, checks whether literal value starts with "/". The mentioned [babel-module issue](https://github.com/codeclimate/codeclimate-eslint/pull/231#issuecomment-291202705) does not appear to be related to this specific rule but a misconfiguration of ESLint.
Add:
* `import/no-restricted-paths` — relies on absolutely resolved module paths
* `node/no-hide-code-modules` — relies on module resolution, also deprecated

Rule Blocklist update

---

bin/circleci-update-yarn-lock

Sometimes the commit messages look like "chore(package)", not
"fix(package)", but we should still run yarn in those cases.
Example: https://github.com/codeclimate/codeclimate-eslint/pull/256
I'm guessing it's just a chore when it's a devDependency.

Update auto-yarn strategy

---

Makefile

We're hitting errors where the `mocha` command is not available. I
believe this is because we were running `yarn` in `/usr/src/app`, and
then trying to run tests in `/code`, where the node_modules aren't
available.
For a sec, I assumed this was related to
https://github.com/codeclimate/codeclimate-eslint/pull/256 but I
confirmed the issue predates that change.

Fix `make test` and `make integration`

---

Dockerfile
Makefile

The idea is to make sure `yarn.lock` gets updated during development in case `package.json` is manually edited.
The dependencies chain in Makefile seems ok, but this changes might turn the flow a bit convoluted as the result
of `make yarn.lock` generate files which invalidates `docker build` cache.
I think there is also room for improving how we generate `lib/docs` and `engine.json` through `Dockerfile` without having
this process to indirectly dependend on `package.json` (`jq > npm install > package.json`)
Please, let me know if this is worth keeping.

Build improvements

---

package.json
yarn.lock

In particular this incorporates the `Fix jsx-indent crash` bug fix.
https://github.com/yannickcr/eslint-plugin-react/releases/tag/v6.10.1

Bumps eslint-plugin-react 6.10.0 -> 6.10.3

---

package.json
yarn.lock

Addresses https://github.com/codeclimate/codeclimate-eslint/issues/271
The greenkeeper jsx-a11y upgrade to 5.0.0 is breaking compatibility with base configs such as airbnb. That is because they incorporated [breaking changes](https://github.com/evcohen/eslint-plugin-jsx-a11y/releases/tag/v5.0.0) such as rule renames.
I'm not sure why this was even allowed as an upgrade, given running `bin/yarn` on master outputs unmet dependency warnings:
```
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "eslint-config-airbnb@14.1.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@^3.0.2 || ^4.0.0".
warning "eslint-config-react-app@0.6.2" has incorrect peer dependency "eslint-plugin-jsx-a11y@^2.0.0 || ^3.0.0 || ^4.0.0".
[4/4] Building fresh packages... …
```

Revert jsx-a11y upgrade to 5.0.0

---

package.json
yarn.lock

[eslint-plugin-ember](https://github.com/netguru/eslint-plugin-ember) is used to enforce best practices more than syntax rules which is handled via `eslint-plugin-ember-suave`

Add support for eslint-plugin-ember

---

package.json
yarn.lock

This pull introduces the WordPress coding standard for ESLint by adding the [eslint-plugin-wordpress](https://github.com/WordPress-Coding-Standards/eslint-plugin-wordpress) package as a dependency.

Add WordPress Standard

---

package.json
yarn.lock

[eslint-plugin-sort-class-members](https://github.com/bryanrsmith/eslint-plugin-sort-class-members) add a rule to  enforce consistent ES6 class member order.

Add support for eslint-plugin-sort-class-members

---

Makefile
package.json
yarn.lock

Adds [eslint-plugin-scanjs-rules](https://github.com/mozfreddyb/eslint-plugin-scanjs-rules).
> These are supplemental rules for ESLint to introduce functionality similar to to what the existing ScanJS rules do.

Add eslint-plugin-scanjs-rules

---

README.md

This PR is a simple typographical change that adjusts the README to match the syntax used in `master`, but to point back to `master`.

eslint-4/README: Fix link back to master

---

package.json
yarn.lock

This PR adds `eslint-plugin-flowtype` back to the `eslint-4` channel, per request by @wfleming in #336.  I do not believe that there is any reason to keep it out.
Let me know if I can be of assistance.

ESLint 4: Add eslint-plugin-flowtype back

---

package.json
yarn.lock

Adding `eslint-plugin-rulesdir` library allows us to load our own custom ESLint rules.
More info here: https://github.com/eslint/eslint/issues/8769

Add eslint-plugin-rulesdir

---

package.json
yarn.lock

Bumps eslint-react-plugin to 7.5.1:
- In response to: https://github.com/codeclimate/codeclimate-eslint/issues/355

Bump eslint-plugin-react to 7.5.1

---

package.json
yarn.lock

Adds the es5 plugin to address #370. Needed so linter can be configured to error on ES2015 features accidentally getting into ES5 files.

Add eslint-plugin-es5

---

package.json
yarn.lock

Update:
* eslint to 4.18.1
* eslint-config-airbnb to 16.1.0
* eslint-plugin-react to 7.7.0
* eslint-import-resolver-webpack to 0.8.4
* babel-eslint to 8.2.2

[eslint-4] Update eslint packages

---

package.json
yarn.lock

- Bump ```eslint-plugin-security``` from ```1.3.0``` to ```1.4.0```
- Fixes https://github.com/codeclimate/codeclimate-eslint/issues/378

Bump eslint-plugin-security to 1.4.0

---

package.json
yarn.lock

Currently `eslint-plugin-vue` exists in master (eslint 3) but codeclimate doesn't have this plugin for eslint 4. This PR adds the support.
It's related to https://github.com/codeclimate/codeclimate-eslint/issues/365

Adding support for eslint-plugin-vue (eslint 4 channel)

---

package.json
yarn.lock

Per [this comment](https://github.com/codeclimate/codeclimate-eslint/pull/371#issuecomment-367753528) on #371 this is a PR to get the eslint-plugin-es5 into the eslint-4 branch.

Add eslint-plugin-es5 to whitelisted plugins

---

package.json
yarn.lock

Also ran `yarn upgrade` to pull in updates we may not have noticed.
The following warnings were generated:
```
warning "eslint-import-resolver-webpack@0.10.1" has unmet peer dependency "webpack@>=1.11.0".
warning "eslint-config-dbk@3.3.2" has unmet peer dependency "lint-staged@>= 6.0.0".
warning "eslint-config-vue@2.0.2" has incorrect peer dependency "eslint@^2.0.0 || ^3.0.0".
warning "eslint-config-vue@2.0.2" has incorrect peer dependency "eslint-plugin-vue@^1.0.0 || ^2.0.0".
```

Add `eslint-plugin-babel`

---

yarn.lock

I'm of the opinion that we should be on the latest (compatible) release of every dependency.
This is the result of running `bin/yarn upgrade` on the master/stable branch.

Update all ESLint 3.x dependencies.

---

yarn.lock

Reverts codeclimate/codeclimate-eslint#400
- Reverting this to resolve the following issue:
```
error: (CC::CLI::Analyze::EngineFailure) engine eslint failed with status 1 and stderr 
ESLint is running with the /usr/local/node_modules/babel-eslint/index.js parser.
WARN: Skipping source/javascripts/swipe.js: it appears to be minified
assert.js:85
throw new assert.AssertionError({
^
AssertionError: ImportDeclaration should appear when the mode is ES6 and in the module context.
at Referencer.ImportDeclaration (/usr/local/node_modules/escope/lib/referencer.js:591:34)
at Referencer.Visitor.visit (/usr/local/node_modules/esrecurse/esrecurse.js:104:34)
at Referencer.Visitor.visitChildren (/usr/local/node_modules/esrecurse/esrecurse.js:83:38)
at Referencer.Program …
```

Revert "Update all ESLint 3.x dependencies."

---

package.json
yarn.lock

Hi, I have a configuration package that I would like to be whitelisted.  Rather than copy and paste and synchronize my linting rules from project-to-project, which has become a maintenance burden, I’ve opted to centralize them [as a package](https://github.com/jacksonrayhamilton/eslint-config-will-robinson).
It would be great if you would whitelist my package so that my company’s configuration will not need to regress back copying and pasting in order to utilize your service for our JavaScript code.

Add `eslint-config-will-robinson`

---

package.json
yarn.lock

**ESLint plugin** erroring with ```TypeError: Cannot read property 'range' of null```.
- possibly related to versioning difference of these dependencies

update airbnb and airbnb base

---

Makefile
README.md
package.json
yarn.lock

Workaround for https://github.com/codeclimate/codeclimate-eslint/issues/430
There were some changes in ESLint-5 way to load plugins that is being tricky to
patch to make the engine work with non-preexisting plugins.
This adds to the engine the plugin needed by the in the issue above.

Add eslint-comments plugin

---

lib/eslint-patch.js
lib/eslint.js
lib/setting_blocklist.js
test/setting_blocklist_test.js

i think this might solve #427 and #426 - since we're already disabling all of the `import/*` rules there's no reason to keep the `import/resolver` settings - this is what's causing these other modules to be instantiated. 
i added local specs but i don't know how to run integration specs inside of the engine/image so i haven't tested that yet.

add setting blocklist

---

package.json
yarn.lock

PR to update the eslint-plugin-vue via:
`bin/yarn upgrade eslint-plugin-vue`
Where 'vue/script-indent' and 'indent' rules are set this upgrade will fix issues with mutually exclusive errors being raised such as:
```
Expected indentation of 2 spaces but found 0. New
Found in components/example.js by eslint
Expected indentation of 0 spaces but found 2 spaces. Fixed
Found in components/example.js by eslint
```

Update eslint-plugin-vue to 5.1.0

---

package.json
yarn.lock

`eslint-plugin-filenames` is present on `master` but didn't make it to the `channel/eslint-4` branch when #319 was closed. It is working for us on ESLint 4 (unsure about 5).

Add eslint-plugin-filenames

---

package.json

Tests were broken in `channel/eslint-4` branch due to PR #420 
```
8 passing (2s)
4 failing
1) eslint integration extends plugin loads the plugin and does not include repeated issues of not found rules:
Error: /usr/local/node_modules/eslint-config-airbnb/rules/react.js:
Configuration for rule "react/jsx-no-bind" is invalid:
Value {"ignoreRefs":true,"allowArrowFunctions":true,"allowFunctions":false,"allowBind":false,"ignoreDOMComponents":true} should NOT have additional properties.
Referenced from: /usr/local/node_modules/eslint-config-airbnb/index.js
Referenced from: /usr/src/app/integration/extends_airbnb/eslintrc.json
at validateRuleOptions (/usr/local/node_modules/eslint/lib/config/config-validator.js:119:19)
at Object.keys.forEach.id …
```

upgrade eslint-plugin-react (7.7.0 -> 7.11.0)

---

package.json
yarn.lock

The updated eslint-plugin-ember includes:
* A number of _recommended_ configuration changes.
* Fixes for several false positives
[eslint-plugin-ember changelog](https://github.com/ember-cli/eslint-plugin-ember/blob/master/CHANGELOG.md#v671-2019-07-02)

Upgrade eslint-plugin-ember in channel/eslint-5

---

yarn.lock

Update several eslint-plugin packages, namely:
-   `eslint-config-airbnb`: `"17.1.0"` -> `"17.1.1"`
-  `eslint-plugin-flowtype`: `"3.9.1"` -> `"3.13.0"`
-  `eslint-plugin-import`: `"2.17.3"` -> `"2.18.2"`
-   `eslint-plugin-jsx-a11y`: `"6.2.1"` -> `"6.2.3"`
-  `eslint-plugin-react`: `"7.13.0"` -> `"7.16.0"`
-  `eslint-plugin-react-hooks`: `"1.6.0"` -> `"1.7.0"`
`eslint-plugin-react` adds a new rule that we were trying to use - `react/jsx-curly-newline` that is only added in `7.14`, and I ended up bumping the versions on several other packages, just minor versions.

Upgrade Eslint plugin packages

---

package.json
yarn.lock

This plugin helps codebases migrate from lodash/underscore to ES6+ based
methods available natively on the browser. Currently it has about 25k
downloads per week. We are currently using it but are blocked from
adding it to the CodeClimate build due to it being missing here.
https://libraries.io/npm/eslint-plugin-you-dont-need-lodash-underscore
https://www.npmjs.com/package/eslint-plugin-you-dont-need-lodash-underscore
Tested against eslintrc.js
```
module.exports = {
extends: [
"plugin:you-dont-need-lodash-underscore/compatible",
]
}
```

Add you dont need lodash plugin

---

yarn.lock

Version 2.1.0 added a recommended setting to apply the recommended
rules. Updating this will allow users to use that in
their eslintrc. Currently analyze will throw an error when it
encounters this recommended option.
Upgraded via CONTRIBUTING.md commands using test instance 
and running against issue's inputs.
Closes #484 
- [Cypress plugin 2.1.0][2.1.0]
- [codeclimate-eslint yarn.lock][codeclimate-eslint]
[2.1.0]: https://github.com/cypress-io/eslint-plugin-cypress/releases/tag/v2.1.0
[codeclimate-eslint]: https://github.com/codeclimate/codeclimate-eslint/blob/0612a739c4c32e096f8049a86ace48b5c4894afc/yarn.lock#L1164

Update eslint-plugin-cypress to 2.11.1

---

Dockerfile
package.json
yarn.lock

Notes:
- The new version of `@typescript-eslint/eslint-plugin` needs node >= 12.0.0.
- Tested this with the repo for which the original problem was reported and it solves it.
- This will require the user to update their rules to adjust to the breaking changes that have been introduced in https://github.com/typescript-eslint/typescript-eslint/blob/master/CHANGELOG.md#200-2019-08-13 (the minimum version for fixing the issue reported by the user is 2.5.0 and after that there are no breaking changes)

Upgrade typescript

---

package.json
yarn.lock

Reproduced issue reported in https://codeclimate.atlassian.net/browse/QUAPL-45 and checked that this update effectively fixes it.
I also did the same update for the eslint-7 channel we added recently https://github.com/codeclimate/codeclimate-eslint/pull/494

QUAPL-45: Update typescript

---

package.json
yarn.lock

This is to be able to use the latest options for the [`react/jsx-no-literals`](https://github.com/yannickcr/eslint-plugin-react/blob/master/CHANGELOG.md#7210---20200922) rule.
I am happy to raise this across the other channels too.
Thanks!

Update eslint-plugin-react to v7.21.0

---

integration/eslint_test.js
lib/eslint6-patch.js
test/eslint6-patch_test.js

Report: https://codeclimate.atlassian.net/browse/QUA-146
**Root causes**
* In `channel/eslint-5` we started using [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint).
* `typescript-eslint` adds some pre-built configuration files that can be use in the `.eslintrc.*` config file to extend configuration.
* In particular, two files trigger the `No rules configured warning`: [this one](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/configs/eslint-recommended.ts) and [this one](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/configs/base.ts).
* The first one has rules defined but it's in `overrides`, which the `CLIEngine` we are using does not support (See supported features …

QUA-146: Fix no rules configured warning

---

package.json
yarn.lock

We use codeclimate in our projects and are getting many errors like the ones below. We presume this is due to the version of `eslint-plugin-ember` that is being used is quite outdated.

Upgrade `eslint-plugin-ember` to `v10.3.0`

---

package.json
yarn.lock

hapi have moved their config to `@hapi/eslint-plugin`.
Add the new package, and keep the old config for backward compatibility.
Refs:
- https://github.com/hapijs/eslint-plugin/pull/20
- https://github.com/hapijs/eslint-plugin/issues/21

Support @hapi/eslint-plugin

---

package.json
yarn.lock

Update the following packages
package|from|to
-|-|-
@typescript-eslint/eslint-plugin| ^3.3.0 | ^4.31.1
@typescript-eslint/parser| ^3.3.0 | ^4.31.1
@eslint-plugin-import|^2.17.3|^2.24.2
https://codeclimate.atlassian.net/browse/QUA-231

QUA-231: update eslint and typescript plugins

---

package.json
yarn.lock

To fix the error detailed in [QUA-388](https://codeclimate.atlassian.net/browse/QUA-388), the `next` package has been installed, and the `eslint-config-next` package has been updated to the matching version `11.1.2`

QUA-388: add next.js and update eslint-config-next

---

README.md
package.json
yarn.lock

Adds the eslint plugin [eslint-plugin-vue-split-by-script-lang](https://www.npmjs.com/package/eslint-plugin-vue-split-by-script-lang).
We need this plugin to be able to lint a vue codebase with both typescript and javascript vue files. Without the plugin, it's not possible to add typescript rules just for `.vue` files that contain typescript.
I followed the steps in CONTRIBUTING.md to add the package and test the changes.

Add eslint-plugin-vue-split-by-script-lang

---

Dockerfile

This PR updates the base image from `node:6.17-stretch` to `node:17.3-bullseye-slim`.
The line `RUN apt-get update && apt-get install -y gnupg` has been added due to an error being thrown in this line:
```
RUN apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg...
```
```
gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
```

QUA-461: update base image

---

Dockerfile

This PR updates the base Docker image for the `eslint-7` channel

QUA-461: update eslint-7 base image

---

Dockerfile

This PR updates the base Docker image for the `eslint-5` channel

QUA-461: update eslint-5 base image

---

README.md
package.json
yarn.lock

Adds the [standard-with-typescript](https://github.com/standard/eslint-config-standard-with-typescript) module.
We would like support for this module so that we can integrate our ESLint setup with Code Climate.
I followed the instructions in the CONTRIBUTING.md and tested the changes.
Fixes #473

Add eslint-config-standard-with-typescript

---

.circleci/config.yml
Makefile

QUA-958: Push images to Dockerhub instead of GCR (eslint-1)

---

.circleci/config.yml
Makefile

QUA-958: Push images to Dockerhub instead of GCR (eslint-2)

---

.circleci/config.yml
Makefile

QUA-958: Push images to Dockerhub instead of GCR (eslint-4)

---

.circleci/config.yml
Makefile

QUA-958: Push images to Dockerhub instead of GCR (eslint-5)

---

.circleci/config.yml
Makefile

QUA-958: Push images to Dockerhub instead of GCR (eslint-6)

---

.circleci/config.yml
Makefile

QUA-958: Push images to Dockerhub instead of GCR (eslint-7)

---

package.json
yarn.lock

This adds in the `eslint-plugin-sonarjs` which should fix issues with repos that use `eslint-5` as a channel who use this plugin in analysis.

add `eslint-plugin-sonarjs` to eslint 5
